Copy changes to the hiring page
Babylonpartners/iOS-Interview-Demo pull request #3
Opened 2017-06-25 19:40 UTC by diegopetrucci

2017-06-25 19:56 UTC, wltrup requested changes

2017-06-25 19:56 UTC, wltrup commented on README.md
> +To make make the whole process more inclusive, we provide three options for applying. Mind you, you only need to submit one. Choose what suits you best:
"make" is repeated.

2017-06-25 19:56 UTC, wltrup commented on README.md
> +Our main aim is to understand how would it be to work with each other, so it'll be for both us and for you. This pair programming / interview session usually lasts from one to two hours.
I'd suggest this, instead:

"Our main aim is to understand how well we would work with you and you with us, so this is also a chance for you to learn about us."

2017-06-25 21:38 UTC, wltrup approved these changes

2017-06-26 08:35 UTC, dmcrodrigues approved these changes
👍

2017-06-26 16:45 UTC, merged